export const LOGIN_REQUEST="LOGIN_REQUEST"
export const LOGIN_SUCCESS="LOGIN_SUCCESS";
export const LOGIN_FAILURE="LOGIN_FAILURE";
export const GET_ADMIN_DATA="GET_ADMIN_DATA"
export const GET_QA_DATA_SUCCESS="GET_QA_DATA_SUCCESS"
export const GET_QA_DATA_FAILURE="GET_QA_DATA_FAILURE"